import Headers from '@/components/Headers';
import TopBar from '@/components/TopBar';
import { GetServerSidePropsContext } from 'next';
import Head from 'next/head'

type Product = {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: {
    count: number;
    rate: number;
  }
}

type Props = {
  products: Product[]
}



export default function Home({ products }: Props) {
  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <Headers />

      <main>
        {products.map(product => {
          return <p>{product.title}</p>
        })}
      </main >
    </>
  )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {

  const products = await fetch('https://fakestoreapi.com/products')
    .then(res => res.json())

  return {
    props: {
      products
    }, // will be passed to the page component as props
  }
}
